name: Create Nuget Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: nuget/setup-nuget@v3
        with:
          nuget-api-key: ${{ secrets.NUGETORGAPIKEY }}
          nuget-version: '5.x'
      - run: |
          nuget pack .nuspec -NoDefaultExcludes
          nuget push Hantsch.CSharp.StyleCop.*.nupkg -NonInteractive -Source https://api.nuget.org/v3/index.json
